name: pss_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  animations: ^2.1.1
  bloc: ^9.2.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.2
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_switch: ^0.3.2
  fpdart: ^1.2.0
  get_it: ^9.2.0
  go_router: ^17.1.0
  iconify_flutter_plus: ^1.0.4
  image_picker: ^1.2.0
  internet_connection_checker_plus: ^2.9.1+2
  intl: ^0.20.2
  meta: ^1.16.0
  paged_vertical_calendar: ^1.1.10
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  syncfusion_flutter_barcodes: ^32.2.7
  timelines_plus: ^1.0.8

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppin/Poppins-Bold.ttf
        - asset: assets/fonts/poppin/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppin/Poppins-Medium.ttf
        - asset: assets/fonts/poppin/Poppins-Regular.ttf
        - asset: assets/fonts/poppin/Poppins-Light.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf
